# Generated by Django 6.0.4 on 2026-05-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
